### ISSUE TITLE
all libraries are missing!!

### ISSUE THREAD

**Issue by Tabarek** [myfreeweb/conatra#1]
i tried to use the code but non of libraries are found 
P.S. i downloaded all the libraries as in the steps 

what i have to do?
please help:( 

![image](https://cloud.githubusercontent.com/assets/24295788/20800064/33dd44a6-b7f5-11e6-99ed-1c1bf0a4e7a5.png)

**Comment by valpackett** [comment]
Looks like you're trying to use EtherCard on an ESP8266? There's no Ethernet on the ESP8266, you have to switch to the WiFi library. Which, by the way, I haven't tested.

I don't actually recommend using Arduino and this library (an ugly C preprocessor hack designed to fit into a Leonardo's tiny memory) with the ESP8266. The ESP is much more powerful!

I use [Sming](https://github.com/SmingHub/Sming). Here's [a repo with my projects](https://github.com/myfreeweb/iot-stuff), it includes a C++ CoAP routing library called `can-has-coap`. It's not well documented or anything though :D

**Comment by Tabarek** [comment]
thats right 
chocolatey seems great tool but it's not familiar to me and idk what to do

**Comment by valpackett** [comment]
What to do? Learn all the things, I guess :) Sorry, I'm not offering ready to use / finished / documented / supported products here, it's just experimental code.
