### ISSUE TITLE
Library not working 

### ISSUE THREAD

**Issue by cvramanan** [myfreeweb/conatra#2]
hi sir , i have followed all the steps mentioned but the coap implementation is not working . Please add a example for coap client .

**Comment by valpackett** [comment]
What do you mean by client? Client on the Arduino? That's not supported. Client on the computer? I still recommend [coap-cli](https://github.com/mcollina/coap-cli)

**Comment by cvramanan** [comment]
I have followed the above steps but the coap-cli don't worked.

**Comment by cvramanan** [comment]
I ment to add a arduino coap client code examples.

**Comment by valpackett** [comment]
There's no support for the arduino being a client.

**Comment by cvramanan** [comment]
I have also tried this code with Firefox cupper plugin(coap client plugin
for Firefox browser ).please help me with the code working . Thanks in
advance.

On 3 Oct 2017 01:44, "Venkat Ramanan" <c.venkataramanan1@gmail.com> wrote:

I ment to add a arduino coap client code examples.

**Comment by valpackett** [comment]
You posted basically no information. Sorry, I can't help you.
